### PR TITLE
GitCheatFinder Added

### PR DESCRIPTION
**Pull request by aritra-tech**
## What kind of change does this PR introduce? (select / add custom)

(new project)

## Description
Git Cheat Finder is an Android Application to easily find the right Git Commands that you want to use. It is made using Kotlin and REST API

- [X] I've read the contribution guidelines.
- [X] I've mentioned my project in the Readme as per guidelines.
- [X] I've checked that my project is not a duplicate project and I have cross checked the exisiting projects in this repository.

## Related Issues

Fixes Issue #10

### CODE REVIEW

**Comment by Greeshma2903** [comment]
Hey @aritra-tech, can you mention your project in the Readme? You can create a linked heading `android` and add the project name underneath in a table.

**Comment by aritra-tech** [comment]
> Hey @aritra-tech, can you mention your project in the Readme? You can create a linked heading `android` and add the project name underneath in a table.

Yeah sure I will do that

**Comment by aritra-tech** [comment]
> Hey @aritra-tech, can you mention your project in the Readme? You can create a linked heading `android` and add the project name underneath in a table.

I have added the project in the README file @Greeshma2903

**Comment by Greeshma2903** [comment]
Great! Thanks for contributing 🚀

**Pull request merged**
