### PR TITLE
Added github pages - README.md

### PR DESCRIPTION
**Pull request by Yashkapure06**
> **Note** to the contributors:
>
> Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](/CONTRIBUTING.md) file first.

## What kind of change does this PR introduce? (select / add custom)

(new project | feature | docs | bug )

## Description

...

- [X] I've read the contribution guidelines.
- [X] I've mentioned my project in the Readme as per guidelines.
- [X] I've checked that my project is not a duplicate project and I have cross checked the exisiting projects in this repository.

Added visit [Visit](https://yashkapure06.github.io/Quick-projects/)

image

## Related Issues

NO Issues

### CODE REVIEW

**Comment by Greeshma2903** [comment]
Hey Yash, thanks for the PR! 

Does it show up like this for you as well? 
image

**Comment by Yashkapure06** [comment]
> Hey Yash, thanks for the PR!
> 
> Does it show up like this for you as well? image

Hey, I think Currently we have everything in flex - or we can say they are in one row
image
We will just have to arrange them in column.. :)

**Comment by Yashkapure06** [comment]
> > Hey Yash, thanks for the PR!
> > Does it show up like this for you as well? image
> 
> Hey, I think Currently we have everything in flex - or we can say they are in one row image We will just have to arrange them in column.. :)

Can I go ahead?

**Comment by Yashkapure06** [comment]
> > > Hey Yash, thanks for the PR!
> > > Does it show up like this for you as well? image
> > 
> > 
> > Hey, I think Currently we have everything in flex - or we can say they are in one row image We will just have to arrange them in column.. :)
> 
> Can I go ahead?

Hey @Greeshma2903 You can [Visit](https://yashkapure06.github.io/Quick-projects/) now! <3

**Comment by Greeshma2903** [comment]
Hey, yes working great! Good to merge 🚀

**Pull request merged**
