### PR TITLE
Added RawTemplate android project

### PR DESCRIPTION
**Pull request by binayshaw7777**
> **Note** to the contributors:
>
> Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](/CONTRIBUTING.md) file first.

## What kind of change does this PR introduce? (select / add custom)

(new project)

## Description
RawTemplate is an Android project or a template that can be used to save a lot of time while developing projects. The project is developed in Kotlin using XML.

- [X] I've read the contribution guidelines.
- [X] I've mentioned my project in the Readme as per guidelines.
- [X] I've checked that my project is not a duplicate project and I have cross checked the exisiting projects in this repository.

## Related Issues

Fixes Issue #19

### CODE REVIEW

**Comment by Greeshma2903** [comment]
Hey @binayshaw7777 can you make the requested changes?

**Comment by binayshaw7777** [comment]
> Hey @binayshaw7777 can you make the requested changes?

What changes??

**Comment by binayshaw7777** [comment]
> Hey @binayshaw7777 can you make the requested changes?

You mean to resolve the merge conflict?

**Review by Greeshma2903 — CHANGES_REQUESTED** [review]

**Comment by binayshaw7777** [comment]
> Hey, I am so sorry, I forgot to submit the review 😬

Yeah, that's what I was going to reply about, anyway it's completely okay. I'll make the changes soon.
Thanks.

**Pull request closed without merging**
