### PR TITLE
chore: projects from swaroopRajwal

### PR DESCRIPTION
**Pull request by swaroopRajwal**
## What kind of change does this PR introduce?

new project

## Description

I've added three projects in `/react` directory
1. octoprofile - built with next, typescript, tailwind
2. sort-visualizer - built with react, typescript, mantine ui, redux toolkit
3. poke-app - built with next, typescript, tailwind, react-query

## Checklist

- [ X ] I've read the contribution guidelines.
- [ X ] I've mentioned my project in the Readme as per guidelines.
- [ X ] I've checked that my project is not a duplicate project and I have cross checked the exisiting projects in this repository.

## Related Issues

Fixes Issue #22

### CODE REVIEW

**Comment by Greeshma2903** [comment]
Great @swaroopRajwal! Can you mention these projects in the README? 
> Add your Project name and a short description in the Projects List section in the [README](https://github.com/Design-and-Code/Quick-projects/blob/main/README.md), under an appropriate language/framework.

**Comment by swaroopRajwal** [comment]
> Great @swaroopRajwal! Can you mention these projects in the README?
> 
> > Add your Project name and a short description in the Projects List section in the [README](https://github.com/Design-and-Code/Quick-projects/blob/main/README.md), under an appropriate language/framework.

Okay!

**Comment by swaroopRajwal** [comment]
@Greeshma2903 done thanks for letting me know about this.

**Comment by Greeshma2903** [comment]
Thanks for contributing! Merged 🚀

**Pull request merged**
